<?php

/**
 * Copyright © 2012 Metrodigi, Inc. All Rights Reserved. Unpublished
 * -- rights reserved under the copyright laws of the United States.
 * USE OF A COPYRIGHT NOTICE IS PRECAUTIONARY ONLY AND DOES NOT IMPLY
 * PUBLICATION OR DISCLOSURE.  THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION
 * AND TRADE SECRETS OF METRODIGI, INC. USE, DISCLOSURE, OR REPRODUCTION IS
 * PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF METRODIGI, INC.
 */

App::import('Vendor', 'Chaucer/Common/ChaucerDomDocument');
App::import('Vendor', 'Chaucer/Epub/TocReader/EpubTocReader');

class Epub3TocReader Implements EpubTocReader
{
    public $path;

    protected $navData;
    
    /**
     * Sets the TOC file
     * @param string $file full path to TOC file including filename
     */
    public function setTocFile($file) 
    {
        $this->path = $file;
    }
    
    /**
     * recusively parse a node.  the node passed is is the parent node of the ol tag, 
     * such as the nav element
     * @param DomNode $node
     * @param DOMXPath $xpath
     * @param int $level
     * @return array
     */
    private function parseTocNode(DomNode $node, DOMXPath $xpath, $level=0)
    {
        $toc = array();
        $childNodes = null;
        $liTags = $xpath->query('ol/li', $node);
        $label = "";
        $href = "";
        foreach($liTags as $liTag)
        {
            $anchor = $xpath->query('a', $liTag)->item(0);
            $href = $anchor->getAttribute('href'); //  $xpath->query('a/@href',$liTag);
            $label = $anchor->textContent; // $xpath->query('a/text()',$liTag);
            $childNodes = $xpath->query('ol', $liTag);
            if(strlen($label)>0 && strlen($href)>0)
            {
                $item['label'] = $label;
                $item['href'] = $href;
                $item['level'] = $level;
                $item['children'] = $this->parseTocNode($liTag, $xpath, $level+1);
                $toc[] = $item;
            }
        }
        return $toc;
    }
    
    /**
     * Parse the table of contents file and populate nav data
     */
    public function parse()
    {
        $this->navData = array();
        $doc = new ChaucerDomDocument();
        $doc->loadHTMLFile($this->path);        
        $xpath = new DOMXpath($doc);
        $xpath->registerNamespace('epub', 'http://www.idpf.org/2007/ops');
        $parentElements = $xpath->query("//nav");
        if(!is_null($parentElements))
        {
            foreach($parentElements as $parentNode)
            {
                if($parentNode->getAttribute('epub:type')=='toc')
                {
                    $this->navData = $this->parseTocNode($parentNode, $xpath, 0,0);
                }
            }
        }
    }

    /**
     * returns an array of toc items generated by parse
     * @return array
     */
    public function getNavData()
    {
        return $this->navData;        
    }
}
